#pragma once

void initializeData();
void displayMenu();
void listStudents();
void listCourses();
void listTeachers();
void listRecords();
void addStudent();
void addTeacher();
void addCourse();
void addRecord();
void deleteStudent();
void deleteTeacher();
void deleteCourse();
void insertStudent();
void insertTeacher();
void insertCourse();
void queryCourse();
void queryTeacher();
void queryRecord();
void queryStudent();
void queryCourse();
void saveRecords();
void saveCourses();
